### ISSUE TITLE
bug(android): the counts on Keyman for Android are not consistent with those on iOS and website

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman.com#318] opened 2022-01-13 03:52 UTC
**Describe the bug**

The counts of monthly and total downloads of a keyboard appears to be zero. What's shown on iOS and website are identical.

Android - iOS - Website
![image](https://user-images.githubusercontent.com/28331388/149261793-94e863ed-d798-44c2-abac-ff9f55739522.png)

**Expected behavior**

The counts should all be consistent.

---

**Keyman for Android:**
 - Device: Pixel XL - API 29
 - OS: Android 10
 - Keyman version: 15.0.176-alpha
 - Target application: Keyman

Note: This doesn't happen on the latest stable version though.

**Comment by MakaraSok** [comment] 2022-01-13 04:11
This actually also appears on iOS of the same version of Keyman.

![image](https://user-images.githubusercontent.com/28331388/149264471-b2f5efe5-1479-4999-881a-4ebcb9b1fcbf.png)

**Comment by mcdurdin** [comment] 2022-01-16 23:58
Yes, this is by design, because the alpha versions use keyman-staging.com rather than keyman.com. Given it only shows on alpha versions, I am not concerned 😁 so will close this issue!

**Closed by mcdurdin** 2022-01-16 23:58 UTC
